name: bot-pr
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to create/update"
        required: true
      commit_message:
        description: "Commit message"
        required: true
      file_path:
        description: "Path to modify"
        required: true
      content:
        description: "New file content (UTF-8)"
        required: true
      pr_title:
        description: "PR title"
        required: true
      pr_body:
        description: "PR body"
        required: false

jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "repo-bot"
          git config user.email "bot@example.com"

      - name: Update file (create/change)
        id: update
        shell: bash
        run: |
          set -euo pipefail
          BR="${{ github.event.inputs.branch }}"
          PATH_TO="${{ github.event.inputs.file_path }}"
          CONTENT="${{ github.event.inputs.content }}"

          git checkout -B "$BR"
          mkdir -p "$(dirna
