name: bot-pr
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to create or update"
        required: true
      commit_message:
        description: "Commit message"
        required: true
      file_path:
        description: "Path to modify (for example docs/hello.txt)"
        required: true
      content:
        description: "New file content (UTF-8)"
        required: true
      pr_title:
        description: "Pull request title"
        required: true
      pr_body:
        description: "Pull request body"
        required: false
        default: ""

jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config user.name "repo-bot"
          git config user.email "bot@example.com"

      - name: Create or update file
